[tools]
node = "20.19.0"

[tasks.bootstrap]
description = "Install Appium automation dependencies"
run = "npm install --prefix automation"

[tasks.appium]
description = "Start Appium server"
run = "export ANDROID_HOME=\"$HOME/Library/Android/sdk\" && npm exec --prefix automation appium -- --config ./automation/appium.config.cjs"

[tasks.test]
description = "Run Appium tests (specify DEMO=01 or DEMO=02)"
run = """
if [ -z "$DEMO" ]; then
  echo "❌ Error: Must specify DEMO env var (e.g., DEMO=01 mise run test)"
  exit 1
fi
export ANDROID_HOME="$HOME/Library/Android/sdk"
npm test --prefix automation
"""
env = { APP_PATH = "demo/$DEMO/build/app/outputs/flutter-apk/app-debug.apk" }

[tasks.build-demo]
description = "Build integration test APK for a demo (DEMO=01 or DEMO=02)"
run = """
if [ -z "$DEMO" ]; then
  echo "❌ Error: Must specify DEMO env var (e.g., DEMO=01 mise run build-demo)"
  exit 1
fi
cd demo/$DEMO
flutter pub get
mkdir -p integration_test
if [ ! -f integration_test/appium_test.dart ]; then
  echo "❌ Error: integration_test/appium_test.dart missing in demo/$DEMO"
  exit 1
fi
flutter build apk --debug --target=integration_test/appium_test.dart
echo "✅ APK built at demo/$DEMO/build/app/outputs/flutter-apk/app-debug.apk"
"""
